name: 'Vue App to Github Pages'
branding:
  icon: 'activity'  
  color: 'blue'
description: 'This Action will Build your Vue Project and deploy it to Github Pages'
runs:
  using: "composite"
  steps:
      - name: Build Vue Project
        run: |
              cd front-end;
              cd matchas-marketplace;
              npm ci;
              npm run build;
              ls
        shell: bash
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3.0.6
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: './front-end/matchas-marketplace/dist'
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v2.0.4
